accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("instructor-dahboard", views.instructor, name="instructor_dashboard_page"),
    path("student-dahboard", views.student, name="student_dashboard_page"),
]

courses/urls.py
from django.urls import path
from . import views

app_name = "courses"
urlpatterns = [
    path("", views.all_courses, name="course_page"),
    path("details", views.single_course, name="single_course"),
    path("events", views.events, name="events_page"),
    path("eventDetails", views.eventDetails, name="event_details_page"),
    path("lessonVideo", views.lessonVideo, name="lesson_video_page"),
    path("lessonText", views.lessonText, name="lesson_text_page"),
    path("lessonQuiz", views.lessonQuiz, name="lesson_quiz_page"),
    path("lessonQuizResult", views.lessonQuizResult, name="lesson_quiz_result_page"),
    path("lessonAssignments", views.lessonAssignments, name="lesson_assignment_page"),
    path("lessonAssignmentsSubmit", views.lessonAssignmentsSubmit, name="lesson_assignment_submit_page"),
]

learningZone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("courses/", include("courses.urls")),
    path("accounts/", include("accounts.urls")),
    # path("liveClasses/", include("live_classes.urls")),
    # path("payments/", include("payments.urls")),
    # path("reviews/", include("reviews.urls")),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"
urlpatterns = [
    path("", views.index, name="home_page"),
    path("about", views.about_us, name="about_page"),
    path("contact", views.contact, name="contact_page"),
    path("instructors", views.instructors, name="instructors_page"),
    path("become-a-teacher", views.becomeATeacher, name="become_a_teacher_page"),
]

accounts/models.py
from django.db import models

# Create your models here.

courses/models.py
from django.db import models

# Create your models here.

live_classes/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

payments/models.py
from django.db import models

# Create your models here.

reviews/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

def instructor(request):
    return render(request, "accounts/instructor.html", {
       "bannerImage": "home-bg.jpg"
    }) 

def student(request):
    return render(request, "accounts/student.html", {
       "headImage": "about-bg.jpg"
    }) 

courses/views.py
from django.shortcuts import render

# Create your views here.

def all_courses(request):
    return render(request, "courses/allCourses.html", {
       "bannerImage": "home-bg.jpg"
    }) 

def single_course(request):
    return render(request, "courses/courseDetails.html", {
       "headImage": "about-bg.jpg"
    })

def events(request):
   return render(request, "courses/events.html")

def eventDetails(request):
   return render(request, "courses/eventDetails.html")

def lessonVideo(request):
   return render(request, "courses/lesson_video.html")

def lessonText(request):
   return render(request, "courses/lesson_text.html")

def lessonQuiz(request):
   return render(request, "courses/lesson_quiz.html")

def lessonQuizResult(request):
   return render(request, "courses/lesson_quiz_result.html")

def lessonAssignments(request):
   return render(request, "courses/lesson_assignments.html")

def lessonAssignmentsSubmit(request):
   return render(request, "courses/lesson_assignments_submit.html")

live_classes/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return render(request, "pages/home.html", {
       "bannerImage": "home-bg.jpg"
    }) 

def about_us(request):
    return render(request, "pages/about.html", {
       "headImage": "about-bg.jpg"
    }) 

def contact(request):
    return render(request, "pages/contact.html", {
       "headImage": "contact-bg.jpg"
    })

def instructors(request):
   return render(request, "pages/instructors.html", {
       "bannerImage": "home-bg.jpg"
    })
def becomeATeacher(request):
   return render(request, "pages/become_a_teacher.html", {
       "bannerImage": "home-bg.jpg"
    })

payments/views.py
from django.shortcuts import render

# Create your views here.

reviews/views.py
from django.shortcuts import render

# Create your views here.

courses/templates/courses/events.html
{% extends "base.html" %}
{% load static %}

{% block body_content %}
<div class="rbt-page-banner-wrapper">
    <!-- Start Banner BG Image  -->
    <div class="rbt-banner-image"></div>
    <!-- End Banner BG Image  -->
    <div class="rbt-banner-content">
        <!-- Start Banner Content Top  -->
        <div class="rbt-banner-content-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Start Breadcrumb Area  -->
                        <ul class="page-list">
                            <li class="rbt-breadcrumb-item"><a href="{% url 'pages:home_page' %}">Home</a></li>
                            <li>
                                <div class="icon-right"><i class="feather-chevron-right"></i></div>
                            </li>
                            <li class="rbt-breadcrumb-item active">All Event</li>
                        </ul>
                        <!-- End Breadcrumb Area  -->

                        <div class=" title-wrapper">
                            <h1 class="title mb--0">All Event</h1>
                            <a href="#" class="rbt-badge-2">
                                <div class="image">🎉</div> 99 Events
                            </a>
                        </div>
                        <p class="description">Event that help beginner designers become true unicorns. </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Banner Content Top  -->
    </div>
</div>

<div class="rbt-counterup-area rbt-section-overlayping-top rbt-section-gapBottom">
    <div class="container">
        <div class="row g-5">
            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/devops.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-calendar"></i>11 Jan, 2025</li>
                            <li><i class="feather-map-pin"></i>IAC Building</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}">International Education Fair 2025</a></h4>
                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->
            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/digital-marketing.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-map-pin"></i>Vancouver</li>
                            <li><i class="feather-clock"></i>8:00 am - 5:00 pm</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}">Painting Art Contest 2020</a></h4>

                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->

            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/digital-product.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-map-pin"></i>Paris</li>
                            <li><i class="feather-clock"></i>8:00 am - 5:00 pm</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}">Histudy Education Fair 2025</a></h4>

                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->

            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/ds-ml.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-map-pin"></i>IAC Building</li>
                            <li><i class="feather-clock"></i>8:00 am - 5:00 pm</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}"> Elegant Light Box Paper Cut Dioramas</a></h4>

                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->

            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/flutter.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-map-pin"></i>Vancouver</li>
                            <li><i class="feather-clock"></i>8:00 am - 5:00 pm</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}">Most Effective Ways Education's Problem.</a></h4>

                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->

            <!-- Start Single Event  -->
            <div class="col-lg-6 col-md-6 col-12">
                <div class="rbt-card card-list-2 event-list-card variation-01 rbt-hover">
                    <div class="rbt-card-img">
                        <a href="{% url 'courses:event_details_page' %}">
                            <img src="{% static 'assets/images/355_240/golan-workshop.png' %}" alt="Card image">
                        </a>
                    </div>
                    <div class="rbt-card-body">
                        <ul class="rbt-meta">
                            <li><i class="feather-map-pin"></i>Paris</li>
                            <li><i class="feather-clock"></i>8:00 am - 5:00 pm</li>
                        </ul>
                        <h4 class="rbt-card-title"><a href="{% url 'courses:event_details_page' %}">Top 7 Common About Education.</a></h4>

                        <div class="read-more-btn">
                            <a class="rbt-btn btn-border hover-icon-reverse btn-sm radius-round" href="{% url 'courses:event_details_page' %}">
                                <span class="icon-reverse-wrapper">
                                    <span class="btn-text">Get Ticket</span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Single Event  -->
        </div>
        <div class="row">
            <div class="col-lg-12 mt--60">
                <nav>
                    <ul class="rbt-pagination">
                        <li><a href="#" aria-label="Previous"><i class="feather-chevron-left"></i></a></li>
                        <li><a href="#">1</a></li>
                        <li class="active"><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#" aria-label="Next"><i class="feather-chevron-right"></i></a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="rbt-separator-mid">
    <div class="container">
        <hr class="rbt-separator m-0">
    </div>
</div>
{% endblock%}

courses/templates/courses/lesson_assignments.html
{% extends "base.html" %}
{% load static %}

{% block body_content %}
<div class="rbt-lesson-area bg-color-white">
    <div class="rbt-lesson-content-wrapper">
        <div class="rbt-lesson-leftsidebar">
            {% include "courses/lesson_navbar.html" %}
        </div>

        <div class="rbt-lesson-rightsidebar overflow-hidden">
            <div class="lesson-top-bar">
                <div class="lesson-top-left">
                    <div class="rbt-lesson-toggle">
                        <button class="lesson-toggle-active btn-round-white-opacity" title="Toggle Sidebar"><i class="feather-arrow-left"></i></button>
                    </div>
                    <h5>The Complete Web Development: From Zero to Expert!</h5>
                </div>
                <div class="lesson-top-right">
                    <div class="rbt-btn-close">
                        <a href="{% url 'courses:single_course' %}" title="Go Back to Course" class="rbt-round-btn"><i class="feather-x"></i></a>
                    </div>
                </div>
            </div>
            <div class="inner">
                <div class="content">
                    <div class="section-title">
                        <h4>The Complete Web Development: From Zero to Expert!.</h4>
                        <div class="bg-color-white rbt-shadow-box">
                            <h5 class="rbt-title-style-3">Your Assignment</h5>
                            <p>Content Here</p>
                            <div class="submit-btn">
                                <a class="rbt-btn btn-gradient hover-icon-reverse" href="lesson-assignments-submit.html">
                                    <span class="icon-reverse-wrapper">
                                            <span class="btn-text">Submit Assignment</span>
                                    <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                    <span class="btn-icon"><i class="feather-arrow-right"></i></span>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="rbt-progress-parent">
    <svg class="rbt-back-circle svg-inner" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
    </svg>
</div>
{% endblock%}

courses/templates/courses/lesson_navbar.html
<div class="rbt-course-feature-inner rbt-search-activation">
    <div class="section-title">
        <h4 class="rbt-title-style-3">Course Content</h4>
    </div>

    <div class="lesson-search-wrapper">
        <form action="#" class="rbt-search-style-1">
            <input class="rbt-search-active" type="text" placeholder="Search Lesson">
            <button class="search-btn disabled"><i class="feather-search"></i></button>
        </form>
    </div>

    <hr class="mt--10">

    <div class="rbt-accordion-style rbt-accordion-02 for-right-content accordion">


        <div class="accordion" id="accordionExampleb2">

            <div class="accordion-item card">
                <h2 class="accordion-header card-header" id="headingTwo1">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" aria-expanded="true" data-bs-target="#collapseTwo1" aria-controls="collapseTwo1">
                        Welcome Learning Zone <span class="rbt-badge-5 ml--10">1/2</span>
                    </button>
                </h2>
                <div id="collapseTwo1" class="accordion-collapse collapse show" aria-labelledby="headingTwo1">
                    <div class="accordion-body card-body">
                        <ul class="rbt-course-main-content liststyle">

                            <li>
                                <a href="{% url 'courses:lesson_video_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-play-circle"></i> <span class="text">Course
                            Intro</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="min-lable">30 min</span>
                                        <span class="rbt-check"><i class="feather-check"></i></span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="{% url 'courses:lesson_text_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-file-text"></i> <span class="text">Introduction</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="rbt-check"><i class="feather-check"></i></span>
                                    </div>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>

            <div class="accordion-item card">
                <h2 class="accordion-header card-header" id="headingTwo4">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" aria-expanded="true" data-bs-target="#collapseTwo4" aria-controls="collapseTwo4">
                        Welcome Lessons <span class="rbt-badge-5 ml--10">1/3</span>
                    </button>
                </h2>
                <div id="collapseTwo4" class="accordion-collapse collapse show" aria-labelledby="headingTwo4">
                    <div class="accordion-body card-body">
                        <ul class="rbt-course-main-content liststyle">

                            <li>
                                <a href="{% url 'courses:lesson_video_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-play-circle"></i> <span class="text">Hello World!
                        </span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="min-lable">0.37</span>
                                        <span class="rbt-check"><i class="feather-check"></i></span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="{% url 'courses:lesson_video_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-play-circle"></i> <span class="text">Values and Variables</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="min-lable">20 min</span>
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>

                            <li>
                                <a href="{% url 'courses:lesson_video_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-play-circle"></i> <span class="text">Basic Operators
                        </span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="min-lable">15 min</span>
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>


                        </ul>
                    </div>
                </div>
            </div>

            <div class="accordion-item card">
                <h2 class="accordion-header card-header" id="headingTwo2">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" aria-expanded="false" data-bs-target="#collapseTwo2" aria-controls="collapseTwo2">
                        Learning Zone Quiz <span class="rbt-badge-5 ml--10">1/2</span>
                    </button>
                </h2>
                <div id="collapseTwo2" class="accordion-collapse collapse" aria-labelledby="headingTwo2">
                    <div class="accordion-body card-body">
                        <ul class="rbt-course-main-content liststyle">
                            <li>
                                <a href="{% url 'courses:lesson_quiz_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-help-circle"></i> <span class="text">Quiz Start</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'courses:lesson_quiz_result_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-help-circle"></i> <span class="text">Quiz Result</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="accordion-item card">
                <h2 class="accordion-header card-header" id="headingTwo3">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" aria-expanded="false" data-bs-target="#collapseTwo3" aria-controls="collapseTwo3">
                        Assignments <span class="rbt-badge-5 ml--10">1/2</span>
                    </button>
                </h2>
                <div id="collapseTwo3" class="accordion-collapse collapse" aria-labelledby="headingTwo3">
                    <div class="accordion-body card-body">
                        <ul class="rbt-course-main-content liststyle">
                            <li>
                                <a href="{% url 'courses:lesson_assignment_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-file-text"></i> <span class="text">Assignments</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'courses:lesson_assignment_submit_page' %}">
                                    <div class="course-content-left">
                                        <i class="feather-file-text"></i> <span class="text">Assignments Submit</span>
                                    </div>
                                    <div class="course-content-right">
                                        <span class="rbt-check unread"><i class="feather-circle"></i></span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>


    </div>
</div>